spring.application.name=day10_SB_Jpa_Employee



#DB Configuration Detail
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:
spril.datasource.username = root
spril.datasource.password = root

spring.jpa.hibernate.ddl-auto= update

